### ISSUE TITLE
lame icon

### ISSUE THREAD

**Issue by tizu69** [omgimanerd/create-advanced-industries#2]
![image](https://github.com/omgimanerd/create-advanced-industries/assets/60812901/b4d23bec-9497-4e7c-8772-670ea798082e)

**Comment by omgimanerd** [comment]
Hahaha I appreciate it, but I actually commissioned an artist to do a pack icon for me. The current icon is just a placeholder.

**Comment by omgimanerd** [comment]
Icon has been updated by 14b7f1263e794163ffc6b2f5c7daf1c342c04404
