### ISSUE TITLE
JEI game crash

### ISSUE THREAD

**Issue by existereoracle** [omgimanerd/create-advanced-industries#9]
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.BakedModel.getQuads(net.minecraft.world.level.block.state.BlockState, net.minecraft.core.Direction, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData, net.minecraft.client.renderer.RenderType)" because "bakedModel" is null

[crash-2024-07-03_01.06.26-client.txt](https://github.com/user-attachments/files/16077440/crash-2024-07-03_01.06.26-client.txt)

[latest.log](https://github.com/user-attachments/files/16077442/latest.log)

**Comment by omgimanerd** [comment]
Thanks for the report, looking into it. It seems like an issue with embeddium and the way Create Mechanical extruder is attempting to render stuff in the JEI category, I will see if I can reproduce.

Was this a one-off crash or were you able to launch the game and continue afterwards?
